name: CI

on:
  # Trigger the workflow on push
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.6.app
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    - name: Build archive
      run: |
        xcodebuild -sdk iphoneos -workspace "ArtNet Light.xcworkspace" \
          -configuration Release -scheme "ArtNet Light" \
          -derivedDataPath DerivedData \
          -archivePath "DerivedData/Archive/ArtNet Light" archive
    - name: Export Archive
      run: |
        xcodebuild -exportArchive \
          -archivePath "DerivedData/Archive/ArtNet Light.xcarchive" \
          -exportOptionsPlist provisioning/App-Store.plist \
          -exportPath DerivedData/ipa
